### ISSUE TITLE
MS03 caused by date format

### ISSUE THREAD

**Issue by si4dev** [congressus/sepa-direct-debit#25]
I received an MS03 error on the whole batch without more details. Via swift.com I finally manage to find the root cause. 

`The value '2016-01-08T20:51:13+01:00' does not respect the format ([0-9]{4}[-][0-9]{2,2}[-][0-9]{2,2}[T][0-9]{2,2}[:][0-9]{2,2}[:][0-9]{2,2}) defined for the CreationDateTime3 datatype. `

This was generated: 
`<CreDtTm>2016-01-08T23:43:08+1:00</CreDtTm>`

and after removing the time zone it was corrected and approved
`<CreDtTm>2016-01-08T23:43:08</CreDtTm>`

**Comment by JelleM-Congressus** [comment]
Hmmm, which bank was that if I may ask? ISO format allows timezones and so does the xsd I believe. Aren't standards fun?

-------- Origineel bericht --------
Van:si4dev <notifications@github.com>
Verzonden:Fri, 22 Jan 2016 13:53:05 +0100
Aan:congressus/sepa-direct-debit <sepa-direct-debit@noreply.github.com>
Onderwerp:[sepa-direct-debit] MS03 caused by date format (#25)

**Comment by si4dev** [comment]
I'm using the internet banking of Rabobank. Maybe different implementations.

**Comment by JelleM-Congressus** [comment]
Hmm strange, I have seen the rabobank accept a lot of these generated files by now. 

-------- Origineel bericht --------
Van:si4dev <notifications@github.com>
Verzonden:Fri, 22 Jan 2016 17:37:55 +0100
Aan:congressus/sepa-direct-debit <sepa-direct-debit@noreply.github.com>
Cc:Jelle van der Molen <jelle@congressus.nl>
Onderwerp:Re: [sepa-direct-debit] MS03 caused by date format (#25)

**Comment by si4dev** [comment]
When I removed the timezone from the < CreDtTm> date then the full xml file with about 10 transactions (FRST and RCUR) was accepted by the Rabo test portal (serviced by swift.com). When I added the time zone it was rejected again with the error message from my initial message.

My live batch is now also approved after removing the timezone.

So either the Rabobank changed the format or maybe you use one of the other two Rabo applications which might accept the time zone, that I cannot test. 

Let me know if I can test / do something.
